### PR TITLE
Decouple the updates from the logging thread

### PR DESCRIPTION
**Pull request by halgari**

### CODE REVIEW

**Comment by Sewer56** [comment]
LGTM

**Comment by Al12rs** [comment]
So this makes it so that a `Commit()` can return before notifications of the commit are necessarily propagated to observers.
I think that changing that behavior might break a lot of assumption, because all the bound data now no longer reflects the commit changes after commit has returned.

I think decoupling the notifications from the Transaction logger thread is the correct move, but I think what we may want is to only return the `Commit()` call after the notifications have also been handled. 

I think otherwise this would break a lot of our code and tests, because we expect our data to be up to date after `Commit()` has finished, but at the same time we want to be able to continue handling new transactions.

**Review by Al12rs — CHANGES_REQUESTED** [review]
I don't think this should be merged as is. I expect a lot of code would break

**Comment by halgari** [comment]
went a different way with this

**Pull request closed without merging**
